// Agent metadata — glyphs, accent colors, display names
export const AGENTS = {
  domain_intelligence: {
    id: 'domain_intelligence',
    name: 'Domain Intelligence',
    glyph: '🧠',
    accent: 'var(--blue)',
    order: 1,
    description: 'Infers domain from model structure, generates targeted probe questions',
  },
  adversarial_probe: {
    id: 'adversarial_probe',
    name: 'Adversarial Probe',
    glyph: '🎯',
    accent: 'var(--blue)',
    order: 2,
    description: 'Runs probe questions through QuerySimulator, builds BehavioralProfile',
  },
  schema: {
    id: 'schema',
    name: 'Schema Agent',
    glyph: '📐',
    accent: 'var(--teal)',
    order: 3,
    description: '11 deterministic rules + LLM analysis of schema configuration',
  },
  dax: {
    id: 'dax',
    name: 'DAX Agent',
    glyph: '⚡',
    accent: 'var(--amber)',
    order: 4,
    description: '9 deterministic rules + LLM analysis of DAX patterns and routing',
  },
  dax_expression: {
    id: 'dax_expression',
    name: 'DAX Expression',
    glyph: '🔬',
    accent: 'var(--amber)',
    order: 4.5,
    description: '8 deterministic rules analyzing measure DAX expressions for anti-patterns',
  },
  xmla: {
    id: 'xmla',
    name: 'XMLA Deep Analysis',
    glyph: '🏗️',
    accent: 'var(--teal)',
    order: 4.7,
    description: '6 deterministic rules on XMLA DMV data — column cardinality, relationships, storage',
  },
  execution: {
    id: 'execution',
    name: 'Execution Agent',
    glyph: '🔥',
    accent: 'var(--red)',
    order: 5,
    description: '9 deterministic rules + LLM analysis of execution performance',
  },
  synthesis: {
    id: 'synthesis',
    name: 'Synthesis Agent',
    glyph: '🔮',
    accent: 'var(--violet)',
    order: 6,
    description: 'Root cause ranking, cross-model patterns, demo readiness verdict',
  },
  monte_carlo: {
    id: 'monte_carlo',
    name: 'Monte Carlo Agent',
    glyph: '🎲',
    accent: 'var(--green)',
    order: 7,
    description: 'Calibrated distributions, 500 simulations, P10/P50/P90 per fix',
  },
  remediation: {
    id: 'remediation',
    name: 'Remediation Agent',
    glyph: '🔧',
    accent: 'var(--green)',
    order: 8,
    description: 'Generates paste-ready artifacts for Prep for AI',
  },
  finding_validator: {
    id: 'finding_validator',
    name: 'Finding Validator',
    glyph: '✓',
    accent: 'var(--teal)',
    order: 9,
    description: 'Validates individual findings for accuracy, severity, and evidence consistency',
  },
  report_validator: {
    id: 'report_validator',
    name: 'Report Validator',
    glyph: '📋',
    accent: 'var(--teal)',
    order: 10,
    description: 'Validates overall report quality, completeness, gaps, and demo readiness',
  },
};

export const AGENT_ORDER = [
  'domain_intelligence',
  'adversarial_probe',
  'schema',
  'dax',
  'dax_expression',
  'xmla',
  'execution',
  'synthesis',
  'monte_carlo',
  'remediation',
  'finding_validator',
  'report_validator',
];
